# Generated by Django 3.1.3 on 2021-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'customer'), (2, 'merchant'), (3, 'admin')], null=True),
        ),
    ]
