# Generated by Django 3.1.3 on 2021-01-05 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dukaapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='categor',
            new_name='category',
        ),
    ]
