# Generated by Django 3.1.3 on 2020-12-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaapp', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_merchant',
            field=models.BooleanField(default=False),
        ),
    ]
