# Generated by Django 3.1.3 on 2021-01-12 20:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dukaapp', '0005_auto_20210112_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='image2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image_2'),
        ),
    ]
