language: python 

services: 
  - postgresql

python:
  - "3.6"

install: 
  - pip install -r requirements.txt 
  # - pip install coveralls

script:
    
    - python manage.py test dukaapp
  # - coverage run --source='.' manage.py test app

# after_success:
#   - coveralls