language: python 

env:
  - SECRET_KEY='342s(s(!hsjd998sde8$=o4$3m!(o+kce2^97kp6#ujhi'
  - DEBUG=True
  - DB_NAME='duka'
  - DB_USER='moringa'
  - DB_PASSWORD='colo1234'
  - DB_HOST='127.0.0.1'
  - MODE='dev'
  - ALLOWED_HOSTS='shitandi-duka.herokuapp.com'
  - DISABLE_COLLECTSTATIC=1
  - EMAIL_USE_TLS=True
  - EMAIL_HOST='smtp.gmail.com'
  - EMAIL_PORT=587
  - EMAIL_HOST_USER='EMAIL'
  - EMAIL_HOST_PASSWORD='EMAIL-PASSWORD'

services: 
  - postgresql

python:
  - "3.6"


install: 
  - pip install -r requirements.txt 
  - pip install coveralls

before_script:
  - psql -c "CREATE USER moringa WITH PASSWORD 'colo1234';" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to moringa ;" -U postgres
  - psql -c "CREATE DATABASE test_duka;" -U moringa
  
  - pip install coverage

script:
    
    - python manage.py test dukaapp
    - coverage run --source='.' manage.py test

after_success:
  - coveralls