language: python 

env:
  - SECRET_KEY: "TEST"

services: 
  - postgresql

python:
  - "3.6"


install: 
  - pip install -r requirements.txt 
  - pip install coveralls

before_script:
  - psql -c  'create database travis_ci_test;' -u postgres
  - psql -c  'create database test;' -u postgres
  # - psql -c "CREATE USER $USER WITH PASSWORD 'colo1234';" # -U postgres
  # - psql -c "GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public to moringa;" # -U postgres
  # - psql -c "ALTER USER $USER CREATEDB;" # -U postgres
  # - psql -c "CREATE DATABASE duka;" #-U postgres
  # - pip install coverage

script:
    
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test
    - coverage run --source='.' manage.py test

after_success:
  - coveralls